# publisher/telegram_publisher.py
# Publishes the daily pick to the Telegram channel via Bot API.
# The message text is generated by Gemma3 running locally via Ollama.
 
import requests
from config.settings import TELEGRAM_BOT_TOKEN, TELEGRAM_CHANNEL_ID, OLLAMA_URL, OLLAMA_MODEL
from typing import Dict
 
 
DISCLAIMER = (
    "\n\n⚠️ <i>Messaggio di test — Smart Cart Lab è in fase di sviluppo. "
    "I dati, i prezzi e i link sono fittizi e generati casualmente. "
    "Non effettuare acquisti basandoti su queste informazioni.</i>"
)
 
 
class TelegramPublisher:
 
    def publish(self, product: Dict | None) -> bool:
        """
        Send the daily pick to the Telegram channel.
        If product is None, send a 'no deal today' message.
        """
        if product is None:
            return self._publish_no_deal()
        return self._publish_deal(product)
 
    def _publish_deal(self, product: Dict) -> bool:
        """Generate message via Ollama and send to Telegram."""
        message = self._generate_message(product)
        if message is None:
            message = self._fallback_message(product)
        message += DISCLAIMER
        return self._send(message)
 
    def _publish_no_deal(self) -> bool:
        """Send a 'no deal worth it today' message."""
        message = (
            "📭 <b>Smart Cart Lab</b>\n\n"
            "Nessuna offerta degna di nota oggi. "
            "Preferiamo non consigliare nulla piuttosto che segnalare qualcosa di mediocre."
            + DISCLAIMER
        )
        return self._send(message)
 
    def _generate_message(self, product: Dict) -> str | None:
        """Ask Ollama to generate the deal message."""
        prompt = (
            f"Scrivi un messaggio Telegram accattivante per annunciare un'offerta del giorno. "
            f"Il prodotto è: {product.get('title')}. "
            f"Costa {product.get('current_price')}€ invece di {product.get('avg_price_90d')}€ "
            f"(prezzo medio degli ultimi 90 giorni). "
            f"Usa un tono entusiasta ma onesto. Aggiungi qualche emoji pertinente. "
            f"Non aggiungere link. Rispondi solo con il testo del messaggio, nient'altro."
        )

        try:
            response = requests.post(OLLAMA_URL + "/api/generate", json={
                "model": OLLAMA_MODEL,
                "prompt": prompt,
                "stream": False,
            }, timeout=60)
            response.raise_for_status()
            result = response.json().get("response", "").strip()
            return result
        except requests.exceptions.RequestException as e:
            print(f"Ollama error: {e}")
            return None
 
    def _fallback_message(self, product: Dict) -> str:
        """Fallback message if Ollama is unavailable."""
        return (
            f"🚀 <b>Smart Cart Lab: Offerta del Giorno!</b>\n\n"
            f"<b>Prodotto:</b> {product.get('title')}\n"
            f"💰 <b>Prezzo attuale:</b> {product.get('current_price')}€\n"
            f"📉 <b>Prezzo medio 90gg:</b> {product.get('avg_price_90d')}€"
        )
 
    def _send(self, message: str) -> bool:
        """Send a message to the Telegram channel."""
        url = f"https://api.telegram.org/bot{TELEGRAM_BOT_TOKEN}/sendMessage"
        payload = {
            "chat_id": TELEGRAM_CHANNEL_ID,
            "text": message,
            "parse_mode": "HTML",
        }
        try:
            response = requests.post(url, data=payload)
            response.raise_for_status()
            return True
        except requests.exceptions.RequestException as e:
            print(f"Error sending message to Telegram: {e}")
            return False
